services:
  web:
    build: .
    volumes:
      - .:/app  # ホストのカレントディレクトリをコンテナの /app にマウント
    environment:
      - FLASK_ENV=development  # デバッグモードを有効化
    command: flask run --host=0.0.0.0  # 外部からもアクセスできるように設定
    ports:
      - "5000:5000"  # ホストの5000ポートとコンテナの5000ポートを接続
